### ISSUE TITLE
Tried using a sprite sheet for social media handles but they wont show up :'v

### ISSUE THREAD

**Issue by Thebeerz** [Thebeerz/web-design-2-independent-project#1]
I put a black background colour on them so I can see they're there and not hiding behind anything. I checked for any spelling error and the illustrator file but can't seem to figure out why it won't show up. Is it best to use img for social media handles?

@HannahDelaney

**Comment by HannahDelaney** [comment]
I'll have a look!

**Comment by HannahDelaney** [comment]
So if you click on the little eyeball icon when you load this project in Markbot, it will take you to the local server version of your site (the one hosted on your computer) and the icons are there. So you're good!

It explains why a bit here: https://learn-the-web.algonquindesign.ca/courses/web-design-2/using-svg-icons/#step-6 

Great theme too ;)
